# Site settings
title: Michael Gregory | Author Writer Mediator
email: mike@emikegreg.com
description: > # this means to ignore newlines until "baseurl:"
  Prototype of the new MikeGreg.com!
baseurl: "http://ryan258.github.io/protomg" # the subpath of your site, e.g. /blog/
url: "http://ryan258.github.io/protomg" # the base hostname & protocol for your site
twitter_username: MikeGregConsult
github_username:
facebook_pagename: Michael-Gregory-Consulting-LLC-129111600525243
linkedin_url: https://www.linkedin.com/in/mikegregconsult 
linkedin_posts_url: https://www.linkedin.com/today/author/142856581
ganalytics_UA: 

# Build settings
markdown: kramdown
